---
version: "3.2"
services:
  elasticsearch01:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    environment:
      - cluster.name=conex-moose
      - node.name=elasticsearch01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: volume
        source: esdata01
        target: /usr/share/elasticsearch/data
    ports:
      - 9200:9200 # We only need to expose this on one node in the cluster
    networks:
      - default
  elasticsearch02:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    environment:
      - cluster.name=conex-moose
      - node.name=elasticsearch02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch01"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: volume
        source: esdata02
        target: /usr/share/elasticsearch/data
    networks:
      - default
  elasticsearch03:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    environment:
      - cluster.name=conex-moose
      - node.name=elasticsearch03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch01"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: volume
        source: esdata03
        target: /usr/share/elasticsearch/data
    networks:
      - default
  logstash01:
    image: docker.elastic.co/logstash/logstash:6.0.0
    environment:
      - XPACK_MONITORING_ELASTICSEARCH_URL=http://elasticsearch01:9200
    volumes:
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
    networks:
      - default
  kibana01:
    image: docker.elastic.co/kibana/kibana:6.0.0
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch01:9200
    networks:
      - default
    ports:
      - 5601:5601

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local

networks:
  default:
    external:
      name: elastic
